CREATE TABLE foo (
    id NUMBER PRIMARY KEY, 
    value VARCHAR2(15) NOT NULL
) TABLESPACE DRY_WHITE_LOVE;

CREATE TABLE bar (
    id NUMBER PRIMARY KEY, 
    value VARCHAR2(15) NOT NULL
) TABLESPACE NICE_RED_MATH;
